const mongoose = require('mongoose')
const Schema = mongoose.Schema

const userSchema = new Schema({
  ad:{
    type:String,
    require:true
  },
  eposta:{
    type:String,
    require:true
  },
  uniqid:{
    type:String,
    require:true
  },
  twTanimli:{
    type:Boolean,
    require:true,
    default:false
  },
  googleTanimli:{
    type:Boolean,
    require:true,
    default:false
  },
  sifre:{
    type:String,
    require:true
  },
  takipci:{
    type:Number,
    require:true,
    default:0
  },
  takipEdilen:{
    type:Number,
    require:true,
    default:0
  },
  amazonListe:{
    type:Array,
    require:false
  },
  aktiviteGoster:{
    type:Boolean,
    require:true,
    default:true
  },
  uyelikTeklifiGoster:{
    type:Boolean,
    require:true,
    default:true
  },
  pushBildirim:{
    type:Boolean,
    require:true,
    default:false
  },
  sadeceDMBildir:{
    type:Boolean,
    require:true,
    default:false
  },
  yaklasanAboneSureBildir:{
    type:Boolean,
    require:true,
    default:true
  },
  aylikBultenGonder:{
    type:Boolean,
    require:true,
    default:true
  },
  yeniYorumBildir:{
    type:Boolean,
    require:true,
    default:true
  },
  yeniBegeniBildir:{
    type:Boolean,
    require:true,
    default:true
  },
  takipEttiklerimdenIndirim:{
    type:Boolean,
    require:true,
    default:true
  },
  canliYayinBildirim:{
    type:Boolean,
    require:true,
    default:true
  },
  yayinSmsBildir:{
    type:Boolean,
    require:true,
    default:true
  },
  lang:{
    type:String,
    require:true,
    default:"de"
  },
  invisible:{
    type:Boolean,
    require:true,
    default:false
  },
  cevrimici:{
    type:Boolean,
    require:true,
    default:true
  },
  forbidden:{
    type:Boolean,
    require:true,
    default:false
  },
  kind:{
    type:String,
    require:true,
    default:"user"
  },
  reset:{
    code: {
      type:String,
      default:null
    },
    time: {
      type:String,
      default:null
    }
  }
},{collection:'kullanicilar',timestamps:true})

const User = mongoose.model("Kullanici",userSchema)
module.exports = User;

